name: Run tests
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y git python3-bs4
      - name: Run tests
        run: |
          python3 ./romhacking.py --config config.json --tests
